version: '3.8'

services:
  backend-dev:
    image: ${DOCKER_USERNAME}/nutribot-backend:dev
    networks:
      - nutri_internal
    environment:
      - NODE_ENV=development

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nutribot-back-dev.rule=Host(`api-dev.nutribot.techrocket.site`)"
      - "traefik.http.routers.nutribot-back-dev.entrypoints=websecure"
      - "traefik.http.routers.nutribot-back-dev.tls=true"
      - "traefik.http.routers.nutribot-back-dev.tls.certresolver=lets-encrypt"
      - "traefik.http.services.nutribot-back-dev.loadbalancer.server.port=3333"

  frontend-dev:
    image: ${DOCKER_USERNAME}/nutribot-frontend:dev
    networks:
      - web
      - nutri_internal

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nutribot-front-dev.rule=Host(`dev.nutribot.techrocket.site`)"
      - "traefik.http.routers.nutribot-front-dev.entrypoints=websecure"
      - "traefik.http.routers.nutribot-front-dev.tls=true"
      - "traefik.http.routers.nutribot-front-dev.tls.certresolver=lets-encrypt"
      - "traefik.http.services.nutribot-front-dev.loadbalancer.server.port=80"

networks:
  web:
    external: true
  nutri_internal:
    external: true
