version: '3.8'

services:
  backend-dev:
    image: ${DOCKER_USERNAME}/nutribot-backend:dev
    restart: always # Garante que suba após crashes de memória
    networks:
      - nutri_internal
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@postgres:5432/nutribot_dev
    labels:
      - "traefik.enable=true"
      # Nome do router único (nutri-back-dev) para evitar conflito
      - "traefik.http.routers.nutri-back-dev.rule=Host(`api-dev.nutribot.techrocket.site`)"
      - "traefik.http.routers.nutri-back-dev.entrypoints=websecure"
      - "traefik.http.routers.nutri-back-dev.tls=true"
      - "traefik.http.routers.nutri-back-dev.tls.certresolver=lets-encrypt"
      - "traefik.http.services.nutri-back-dev.loadbalancer.server.port=3333"

  frontend-dev:
    image: ${DOCKER_USERNAME}/nutribot-frontend:dev
    restart: always
    networks:
      - web
      - nutri_internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nutri-front-dev.rule=Host(`dev.nutribot.techrocket.site`)"
      - "traefik.http.routers.nutri-front-dev.entrypoints=websecure"
      - "traefik.http.routers.nutri-front-dev.tls=true"
      - "traefik.http.routers.nutri-front-dev.tls.certresolver=lets-encrypt"
      - "traefik.http.services.nutri-front-dev.loadbalancer.server.port=80"

networks:
  web:
    external: true
  nutri_internal:
    external: true
